### PR TITLE
User Indicator (For discussion not merge)

### PR DESCRIPTION
**Pull request by JoshStrobl**
## Preface

This "pull request" is a lie. There is no pulling to be done here, at least not yet, this PR is meant to be an open discussion thread, prior to any git squashing and merge into master, to enable:

1. Code review. Please, I'm still new to Vala. *Don't hesitate to be brutal.* The point is to have quality code entering master, ya?
2. Discussion about implementation details, assistance in worldly manners, learning together and general group kumbaya stuff.

It is fully expected for everything here to be shot down. That's okay, that is what **more commits** and proactive code review is for. This is basically my first attempt at something larger than a few lines of diff in Vala.

## What is the User Indicator

According to the lovely TODO, a replacement for the power menu (really, a `Gtk.Image` with the shutdown symbolic icon) should be provided to enable individuals to have a more accessible applet for common functions like logout, restart, shutdown, etc.

### Preemptive FAQ

**Question**: Why is it called User Indicator?
**Answer**: It is called the User Indicator because it provides information that is not just pertaining to system operations. The intention is to eventually provide a Switch User function via this indicator as well, and I wanted to put more emphasis on user-oriented functionality.

In my opinion, a "Power Menu" doesn't fully describe the functionality of this indicator and I wanted to avoid confusion by the user as to what the applet does.

**Question**: But there isn't a Switch User function in this PR?
**Answer**: No, there isn't. Why? Because I'm a scrub and have no idea how it should be implemented. I'll get into that later.

**Question**: Inspirations?
**Answer**: Code from Raven, wm, budgie-menu, DBusInterface stuff from the elementary folks. [Freedesktop.org](http://freedesktop.org).

## Design

This User Indicator has been designed in a way to be completely separate from the status applet. The UserIndicatorWindow is modeled after the Budgie Menu and because **real** Gtk.Popovers are too limiting (seriously, you can't even use Gtk's (Image)MenuItems). I wanted pretty pictures, okay? Don't judge me for my taste.

The User Indicator depends on:
- accountsservice >= 0.6.40

accountsservice dep: Needed to getting the user's image, real name, and will be needed in the future for user switching.

### Screenshot

This is a screenshot of what it looks like. No, not a mockup, this all works. Ignore differences in darkness, doesn't reflect reality.

current_userindicator

## Current features

- User section
 - Provides user's avatar or fallback.
 - Provides user's "real name" or falls back to username.
 - Supports dynamically changing both and updating.
 - Logout
- Lock (locks the system)
- Suspend (suspends via logind **and** locks the system, for security purposes)
- Restart
 - Pulls up dialog
- Shutdown
 - Pulls up dialog

### Context-aware dialogs

Not entirely sure how this should work, currently it just does the same calls from `powerstrip.vala` in the Raven codebase, which fires up the same dialog and regardless of the action, it still says "Power off" and provides **all** the options.

What do I want it to do ideally? Pull up a context-aware dialog for reboot and shutdown, providing the user context-aware information ("are you sure you want to logout?") and Cancel / Yes options.

### Switch Users

While pulling in multiple users via accountsservice isn't the issue here, I don't really know how user switching is or should work, and thus I need your help. Is there work that needs to be done on the WM side of things? Should I use logind?

I'm thinking the Switch User's MenuItem (commented out) should pull up a separate, centered dialog on the user's current screen, that shows the list of users they can switch to.

Do I honestly think a Switch Users functionality is *really* needed? No. Frankly I think Logout is sufficient, but I'd be happy to implement (or help implement) if desired by others.

## TODO

- [ ] Implement context-aware dialogs
- [ ] User switching (probably?)
- [ ] Get the approval from our benevolent master @ikeydoherty

## Related Issues

- #309 : Suspend and Hibernate
- #404 : [Request] Add "Change user" to logout dialog 
- Solus Project BTS: [#552 [Feature request] Improved shutdown menu options](https://bugs.solus-project.com/show_bug.cgi?id=552)

### CODE REVIEW

**Comment by GrisuProjects** [comment]
> What do I want it to do ideally? Pull up a context-aware dialog for reboot and shutdown, providing the user context-aware information ("are you sure you want to logout?") and Cancel / Yes options.

I am not sure about such strings in terms of UX... Simple strings like "Shutdown?" are much more straight forward in my opinion

Reference: [Writing style - Google design guidelines](https://www.google.com/design/spec/style/writing.html#writing-language)

**Comment by apolitech** [comment]
what about adding a shutdown time? like 15-30-60-90-120 min

**Comment by ikeydoherty** [comment]
I'll accept a rebase of this without much discussion.

**Comment by ikeydoherty** [comment]
Merging, thanks!

**Comment by TheAifam5** [comment]
I think user switching its not needed. That handle login manager.

**Pull request merged**
