### PR TITLE
Bugdie desktop screensaver

### PR DESCRIPTION
**Pull request by City-busz**
## Description
ince GNOME 40 provides a DBus service activation file, usually the DBus path is allocated by gnome-shell before gnome-screensaver runs. This change kills gnome-shell before starting gnome-screensaver, so it can run without problems.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Not the correct way to solve this. We already have changes in our gnome-screensaver fork called https://github.com/getsolus/budgie-screensaver, which should be used with Budgie, and there are other planned changes in that fork.

**Comment by JoshStrobl** [comment]
@City-busz As you can see from the referenced commit in budgie-screensaver, killing of the gjs process that handles the screensaver interface should (and now is) done there. There was supplemental required work to ensure the screensaver could actually queue up for the interface bus and immediately take over once gjs died.

**Comment by City-busz** [comment]
Okay, that's sound reasonable. I'll check if I can replace gnome-screensaver with budgie-screensaver on Arch Linux. Currently we have several patches for gnome-screensaver, so I'll have to check if any of them needed for budgie-screensaver:
https://github.com/archlinux/svntogit-community/tree/packages/gnome-screensaver/trunk

**Comment by JoshStrobl** [comment]
Sounds good. I should be tagging budgie-screensaver v4.0 and budgie-destop 10.5.3 next Tuesday, so I would encourage that to be packaged upon its release to ensure continued functional locking of Budgie. I will be updating our wiki's OS Integration page upon the release of both to reflect the requirement.

**Comment by City-busz** [comment]
The budgie-screensaver looks good, but I will omit the file
`/usr/share/dbus-1/services/org.gnome.ScreenSaver.ForBudgie.service`,
 because it causes that budgie-screensaver runs also in GNOME (Xorg) session, which should not happen.

**Comment by JoshStrobl** [comment]
@City-busz Interesting. Instead of omitting the file, we should probably fix the issue right? :P

**Comment by City-busz** [comment]
Since the screensaver is autostarted in Budgie, this D-Bus service activation file is not so important I think. It's only useful if the screensaver process crashes for some reason.
Maybe the screensaver process could guess somehow if it's run under GNOME or in Budgie, and exit immediately if found the former.

**Comment by JoshStrobl** [comment]
> Maybe the screensaver process could guess somehow if it's run under GNOME or in Budgie, and exit immediately if found the former.

@City-busz yea that's what I am thinking as well. I'll see about doing that, until then I suppose you can remove the file.

**Comment by City-busz** [comment]
Or it's also possible to change the DBus name as it was implemented (and then reverted) in this commit:
https://github.com/getsolus/budgie-screensaver/commit/e2709d75629b5eb0602f21f1133aa09a1f7b9e67

If the DBus names are different, then it wouldn't be a problem as GNOME would never activates it.

**Comment by JoshStrobl** [comment]
@City-busz Should be sorted as of https://github.com/getsolus/budgie-screensaver/commit/b9e990045b4cc4e832377fe6db29090c00630b1e

**Comment by City-busz** [comment]
I'm not sure if it's the best solution, but it's working. Thanks! :)

**Comment by City-busz** [comment]
I see that you finally removed the D-Bus activation file, which is good, because I found that it breaks the screen locking with the specified keybinding in GNOME.

Could you please revert this commit too?
https://github.com/getsolus/budgie-screensaver/commit/b9e990045b4cc4e832377fe6db29090c00630b1e

Checking the DE is not needed if the D-Bus activation file is not present, and someone may want to use budgie-screensaver outside of Budgie in custom sessions.

**Comment by JoshStrobl** [comment]
I don't plan on supporting Budgie Screensaver outside of Budgie itself.

**Comment by City-busz** [comment]
I reverted it in a downstream patch in the Arch Linux package for now.

**Pull request closed without merging**
