### PR TITLE
Fix show desktop applet

### LINKED ISSUE #1406: Show Desktop applet no longer restores
**Operating System**: Solus 3.9995
**Budgie version**: budgie-desktop v10.4-55-g995e85e5

**The issue encountered**
The Show Desktop applet minimises all windows, but not longer restores them on a second click.

**Steps to reproduce the issue**
Add the Show Desktop applet to a panel.
Have windows visible
Click on the applet icon
Click again

### PR DESCRIPTION
**Pull request by yursan9**
Change the old implementation from using Wnck API, to manually
minimizing windows and keeping the reference.
fix #1406

### CODE REVIEW

**Comment by JoshStrobl** [comment]
So instead of storing a list of Wnck.Windows, I think we should have a list of the Wnck.Window's `ulong` xid. Reasoning is when we go to unminimize the window, we're not actually checking if it exists, and there is no state_changed for when a window gets closed. So we may attempt to minimize a window that no longer exists. Alternatively, if we store the xid, we can use the `Wnck.Window.@get()` and pass the ulong xid. If the window exists, it'll be a Wnck.Window instead of null, and therefore we'll know the window still exists before performing an action.

**Comment by yursan9** [comment]
Well, I guess that could works. I only skim along the Wnck's spec documentation and valadoc to implement the solution. I'll try your suggestion @JoshStrobl

**Comment by yursan9** [comment]
Wait, I seem to break something

**Comment by yursan9** [comment]
@JoshStrobl I think this is good enough. Can't really think up another edge case for improvement

**Comment by JoshStrobl** [comment]
Merged, thanks again!

**Pull request merged**
