### PR TITLE
Update the Notification and Policykit images

### PR DESCRIPTION
**Pull request by Jacalz**
This pull request updates the images for Notifications and Policykit to using Plata theme for better consistency with the other screenshots. There really inst much more to it...

### CODE REVIEW

**Comment by JoshStrobl** [comment]
I do agree that those look way better but can we get the Notification one showing actions? You can do so using Rhythmbox :slightly_smiling_face:  Thanks!

**Comment by Jacalz** [comment]
I didn't know how to do that, thanks for the information. Will see to get this updated later today 👍

**Comment by Jacalz** [comment]
I have now changed to using a new screenshot of the `Notification.png` file :slightly_smiling_face: 
I changed up the song because I didn't have any Queen albums, but I chose a song with a known singer and a short name that didn't truncate of the visible area. I also made sure that there were the exact same amount of pixels on every side of the notification in the image :+1:

**Comment by JoshStrobl** [comment]
> I changed up the song because I didn't have any Queen albums

It's fine, I'm not that much of a fan of Queen anyways. Wasn't ever my image :P

**Comment by Jacalz** [comment]
> > I changed up the song because I didn't have any Queen albums
> 
> It's fine, I'm not that much of a fan of Queen anyways. Wasn't ever my image :P

I meant compared to my old image ;)

**Pull request merged**
