### PR TITLE
raven: add some margin to the NotificationClone timestamp label

### PR DESCRIPTION
**Pull request by cybre**
**Before**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**After**
screenshot from 2016-07-13 21-38-43

### CODE REVIEW

**Comment by cybre** [comment]
I have also changed `margin_right` to `margin_end` because `margin_right` and `margin_left` are deprecated.

**Comment by Justinzobel** [comment]
Nice much neater, screenshots always help noobs like me :D

**Comment by ikeydoherty** [comment]
Commit messages help maintainers like me, what exactly is happening here?

**Comment by cybre** [comment]
A margin of 4px is added to the "start" of the timestamp label to separate it (in terms of space) from the notification title.

I went with 4px because you already have a 4px margin on the right (which I changed to "end") side of the timestamp label.

**Comment by ikeydoherty** [comment]
Ah right, ty :]

**Pull request merged**
