### PR TITLE
[WIP] Update front matter of README.md

### PR DESCRIPTION
**Pull request by serebit**
## Description
The Budgie readme is a bit of a mess above the fold. Some images are broken, there are a few images that are a bit messily separated by newlines. I think an update is needed. In this PR, I've made the following changes:

- Fixed links that lead nowhere and images that don't link correctly
- Moved some single-sentence bits into badges underneath the initial header
- Added a GitHub release badge

I intend to make the following change:

- Create a header image that contains the Budgie logo, the text "Budgie Desktop", and subtext "a Solus project" with the Solus logo.

Feedback is welcome.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Review by JoshStrobl — CHANGES_REQUESTED** [review]
Let's put the main desktop image above the header, simply looks better IMO and the "above the fold" argument is slightly flawed given the *actual* above the fold content is the repository content. You'd have to scroll down to see the readme anyways.

**Comment by serebit** [comment]
budgie-header-render

This is what I had in mind for the header image I was talking about, after some design iteration. If you like this, I'll replace the H1 text with it, but if not then the H1 text will stay.

**Comment by JoshStrobl** [comment]
h1 text stays, please use the feedback I provided on your PR.

**Comment by serebit** [comment]
Feedback has already been noted, working on specifics. Will be pushing an update in a few minutes.

**Comment by serebit** [comment]
The indexed PNGs look equivalent to the naked eye, but are *significantly* smaller. Should help with page load times.

**Review by JoshStrobl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
