### PR TITLE
Set XDG_CURRENT_DESKTOP (fix #308)

### LINKED ISSUE #308: Budgie-desktop session failed to start since v10.2.2
I start Budgie Desktop with `startx`, my .xinitrc contains `exec gnome-session --session=budgie-desktop`.
Since v10.2.2, Budgie-session fails to start (it works with v10.2.1): panel and WM don't start. I can start them manually.

Using up-to-date Arch Linux, tested on 3 hosts (i686 and x86_64) including 2 VMs.

I attach gnome-session log (--debug option enabled): [gnome.txt](https://github.com/solus-project/budgie-desktop/files/76939/gnome.txt)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29565239-budgie-desktop-session-failed-to-start-since-v10-2-2?utm_campaign=plugin&utm_content=tracker%2F593746&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F593746&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by X0rg**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
So the budgie-desktop script is provided only for the display managers launching Budgie, which already set this variable. Would it not be better to have a `start-budgie` script ?

**Comment by X0rg** [comment]
Can you think it would cause problem for display managers?
I have read `startxfce4` script, I'm not sure it's what Budgie need.

Personally, I'm not convinced to have 2 scripts (one for display managers, one for xinit).

**Comment by ikeydoherty** [comment]
Ok so here's what I'm thinking..

This should only be done if the variable isn't *already* set (To enable local modification etc)

Step 2, we move away from GNOME Session again. Create a super simple session management util that exports variables that *haven't* been correctly setup, to ensure it always "just works"

**Comment by X0rg** [comment]
Improved in 60a65e1.

So, if I understand, the idea is to start the budgie-session without using gnome-session?

**Comment by ikeydoherty** [comment]
Yeah we need to drop gnome-session I believe

**Comment by ikeydoherty** [comment]
Merged btw, thanks!!

**Pull request merged**
