### PR TITLE
Change Always on Top to CheckMenuItem.

### PR DESCRIPTION
**Pull request by JoshStrobl**
Changing to CheckMenuItem enables easier determination of AOT state.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Dumb question - how well tested is this? We used checkboxes before and it would cause mutter to suicide due to the signal fighting

**Comment by JoshStrobl** [comment]
So it hasn't been suiciding but I *just* noticed it doesn't update when toggling Always on Top via the IconTasklist. So it gets easily confused. Poor little windows... :cry:

**Comment by ikeydoherty** [comment]
So I think we can likely make it check first if the window is AOT, but that would mean ensuring we don't fire any signals either.. Either by destroying the menu each time its used or doing nasty signal buggery

**Comment by JoshStrobl** [comment]
Probably "nasty signal buggery" would be best. As mentioned in IRC:

For the IconTasklist's Button.vala, we can probably expand on the `on_state_changed` signal handler for `Wnck.Window` to ensure that keeps updated with the Window AOT status, since it provides `Wnck.WindowState.ABOVE` and `Wnck.WindowState.BELOW`.

On the Mutter side of things probably via `windowmenu.vala`, we *hopefully* can use the raised or position-changed signals on windows to update its right-click menu's AOT checkbox status.

References:
- http://valadoc.org/#!api=libwnck-3.0/Wnck.Window
- http://valadoc.org/#!api=libwnck-3.0/Wnck.WindowState
- https://developer.gnome.org/meta/stable/MetaWindow.html#MetaWindow-focus

**Comment by ikeydoherty** [comment]
Closing for now as I don't wanna do the Vala unbuggery just to do it again in C. We'll implement the feature in C, sorry bud

**Pull request closed without merging**
