### PR TITLE
Add mutter-9 compatibility (GNOME 41)

### PR DESCRIPTION
**Pull request by sham1**
## Description

This set of patches adds mutter-9  (GNOME 41) compatibility.

Changes:

- Added Mutter-9 compilation VAPI and built against it
- Added `HAVE_MUTTER_9` conditional
- Made `device_id` usage in `src/wm/shim.vala` be used both for `mutter-8` and `mutter-9`
- Fixed `background.vala` since `Clutter.Color.from_string` is no longer a static method, but instead requires an instance
- Made `src/wm/main.vala` use the new `Meta.Context`-class introduced in `mutter-9` that replaced a lot of the calls into stand-alone functions in the `Meta`-namespace.

I have tested this patch on Fedora 35, for which I made the patch before deciding to upstream it, and it works fine, but it should probably be checked more thoroughly.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Review by JoshStrobl — CHANGES_REQUESTED** [review]
Looks similar to the work I had locally :grin: Let's go ahead and drop everything except Mutter 9 + latest GNOME stack (41) support however (that's what I did locally).

**Comment by sham1** [comment]
Real life got slightly in the way, so that's why nothing has happened.

Anyway, by dropping everything else but the stack support, do you mean that everything except the VAPI and meson changes should be dropped? Since all of these commits are necessary for proper functioning and building of the WM.

**Comment by JoshStrobl** [comment]
"Anyway, by dropping everything else but the stack support, do you mean that everything except the VAPI and meson changes should be dropped? Since all of these commits are necessary for proper functioning and building of the WM."

No, I mean GNOME 40 and below support should be dropped and the deps updated respectively. If you feel that might be a bit out of your league, that's okay, I can do it post-merge if needed.

**Comment by sham1** [comment]
Oh I see. Yeah, maybe it'd be a bit daunting because of all the changes. And besides, it's probably not appropriate for this PR since all this is supposed to do is just to get the thing to work and build on the GNOME 41 stack.

So, I suppose the next thing should be squashing?

**Comment by JoshStrobl** [comment]
Yea, feel free to squash. I can handle the cleanup post-merge :) Thanks again!

**Pull request merged**
