### PR TITLE
Added backlight brightness widget

### PR DESCRIPTION
**Pull request by Grmume**
I'm using the budgie-desktop on my laptop on arch linux and I've been missing a simple way to control the backlight of my screen. I developed a simple widget for raven which controls the backlight using the acpi kernel module for video (based on the sound.vala widget).
The widget looks for a compatible backlight controller on creation (in /sys/class/backlight/) and checks if the user has permission to write to the brightness file. If successful the widget is added to raven.
This should work under wayland too (although I haven't tested it).

### CODE REVIEW

**Comment by ikeydoherty** [comment]
I have a concern about this, i.e. whether we should be directly interacting with the sysfs. Perhaps better to use `org.gnome.SettingsDaemon.Power.Screen` ?

**Comment by Grmume** [comment]
I can't seem to find a variable in dconf-editor which lets me adjust the screen brightness(I guess that's what you meant, right?)...I found other tools which adjust the screen brightness by using /usr/lib/gnome-settings-daemon/gsd-backlight-helper --set-brightness and --get-brightness. Using the gsd-backlight-helper would make sure the brightness can be changed without the need to change the permissions on the /sys/class/backlight/*/brightness file, so I guess I will implement that method tomorrow.

**Comment by ikeydoherty** [comment]
Sorry I meant the dbus-interface

**Comment by ikeydoherty** [comment]
Closing this due to lack of response. Still interested in seeing something implemented like this, maybe we can meet on IRC some time?

**Pull request closed without merging**
