### PR TITLE
Replace na-tray with mate-desktop's fork

### PR DESCRIPTION
**Pull request by serebit**
## Description
This fixes several issues with the system tray, reduces the Vala code required for the applet itself, and allows the tray to start with the panel instead of after a delay. Solved issues that I've seen:
- Some tray icons not appearing on boot or login
- Doubled padding every time the applet changes position

This update also sorts the system tray icons instead of ordering by time launched, which means they'll be in the same position every boot and even when the panel is refreshed.

Verified with the panel in every position (top, bottom, left, right).

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by Staudey** [comment]
This seems to cause gigantic tray icons on my system:

Screenshot from 2020-05-25 20-59-56

**Comment by serebit** [comment]
> This seems to cause gigantic tray icons on my system

Oh, that's fun. Try replacing `src/applets/tray/TrayApplet.vala` with the attached and see if anything changes.

[TrayApplet.zip](https://github.com/solus-project/budgie-desktop/files/4678578/TrayApplet.zip)

**Comment by Staudey** [comment]
@serebit If I replace/patch that file then try icons work like normal again.

**Comment by serebit** [comment]
@Staudey Perfect. I'll amend the PR—thanks for the testing!

**Comment by EbonJaeger** [comment]
So far this is working pretty well for me.

One thing I do notice is that some indicators change the size of existing program icons when being added to the tray (Teamviewer does this). This isn't necessarily a bad thing since they become slightly bigger and thus easier to see, but Teamviewer doesn't have the same padding as the other icons; it's smushed up against the icon next to it. I don't know if this is Teamviewer doing it wrong, or if its a side-effect of this patch. Either way, it doesn't seem like a major issue so far, just an oddity.

Will edit with pictures.

**Comment by JoshStrobl** [comment]
Do you want to update your patch to reference the commits you believe it solves? e.g. #1932? Does it fix #1249? Are you able to reproduce #1419 or #1420 with this patch?

**Comment by serebit** [comment]
It definitely fixes #1932. I can't reproduce #1419 or #1420, but I believe it does fix #1249.

**Comment by serebit** [comment]
Updated to partially fix #1954, and improved spacing between icons.

**Comment by serebit** [comment]
This does have an issue where icons shrunken by a panel side change (e.g. from bottom to left) retain their size when swapping back to bottom. I do think that's less of a concern than icons not appearing at all, though.

**Comment by serebit** [comment]
Closing in favor of my system tray rewrite, since this one has problems too.

**Pull request closed without merging**
