### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by libcg**
Build broke with clutter 1.23.4. Fix this.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Surely it would be better to fix the problem with clutter? What is the build failure?

**Comment by libcg** [comment]
CLUTTER_ACTOR_IS_VISIBLE has been deprecated in favor of clutter_actor_is_visible only available in the upcoming clutter 1.24 release :/

**Comment by ikeydoherty** [comment]
The alternative to this is ugly #ifdefs which will only grow and make this worse. Alright we'll pull this in till we have a more complete solution. Cheers @libcg :]

**Comment by libcg** [comment]
I agree. Thanks for being so quick

**Pull request merged**
