### PR TITLE
Desktop override

### PR DESCRIPTION
**Pull request by City-busz**
## Description
This left the default settings for GNOME, and override them only for the Budgie session. Also add override for the desktop background, because the default one is animated, which is not supported by Budgie background renderer.

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Review by JoshStrobl — CHANGES_REQUESTED** [review]
This commit, namely the background change, is entirely based on the assumption that Budgie is being shipped with no additional branding changes being involved, including something as minor as the wallpaper (not to mention it's assuming that gnome-backgrounds are installed, which aren't a requirement and shouldn't be one). In the case of Solus, we have our own branding package, which sets the background appropriately, just as how we do it with the GNOME Edition we ship.

The appropriate thing to do is ship your Budgie package with a set of branding packages that fit your operating system. If you aren't the downstream package maintainer for Budgie Desktop on your operating system, I encourage you to reach out to them instead. But this isn't going to be merged in as is.

**Comment by City-busz** [comment]
Arch Linux ships vanilla packages without additional branding, so we use the default GNOME themes for all GTK-based desktop environments. Ideally Budgie should support animated backgrounds, so it can use the default one configured in gsettings-desktop-schemas, but until that we need a workaround.

Would you accept this PR if I remove the background override setting?

**Comment by JoshStrobl** [comment]
Yes, in my opinion it would be acceptable for the patch to just be the respective changes for `[org.gnome.mutter:Budgie]` and `[org.gnome.desktop.wm.preferences:Budgie]` without the background default change.

I'll see about supplying / copying a wallpaper from Solus to ship as a default for Budgie 10.5.3 so there isn't a requirement for the gnome-backgrounds package.

**Comment by City-busz** [comment]
I updated my PR.

**Comment by JoshStrobl** [comment]
LGTM, thanks!

**Comment by JoshStrobl** [comment]
@City-busz Could you let me know if 4b9542247f09c983fa23c64be3edab30d7a642e8 resolves your issue with Budgie's lack of wallpaper?

**Comment by City-busz** [comment]
Thanks! The screensaver background still uses the default GNOME background so you probably also want to override it (either same as the desktop background or something else):
```
[org.gnome.desktop.screensaver:Budgie]
picture-uri = 'file:///usr/share/backgrounds/budgie/default.jpg'
```

**Comment by JoshStrobl** [comment]
Yea, will get that added as well.

**Pull request merged**
