### PR TITLE
Clock Settings

### PR DESCRIPTION
**Pull request by LaraCraft93**
The settings are shown when the user clicks on the clock with right click.

clock_settings

### CODE REVIEW

**Comment by Justinzobel** [comment]
I like this @ikeydoherty pleeease :D .. either in budgie settings dialog or as shown here (prefer in bsd though).

**Comment by crutchcorn** [comment]
This = nice. Plz @ikeydoherty?

**Comment by ZetaHunter** [comment]
Thats very nice idea, except Date & Time style can be changed using Gnome Tweak Tool already.
So this kinda loses point for the clock applet specificly, I'd love to have menus for applets though.
Like for example ability to pin applications to task bar.

**Comment by Justinzobel** [comment]
You can already pin items to the taskbar..

**Comment by ZetaHunter** [comment]
Yes, that's what I found out 5minutes later and edited my message, alas notifications do send fixed time value rather then just dynamic link to issue.

On Apr 7, 2015, Justin <notifications@github.com> wrote:
>You can already pin items to the taskbar..
>
>On Tue, 7 Apr 2015 at 07:38 ZetaHunter <notifications@github.com>
>wrote:
>
>> Thats very nice idea, except Date & Time style can be changed using
>Gnome
>> Tweak Tool already.
>> So this kinda loses point for the clock applet specificly, I'd love
>to
>> have menus for applets though.
>> Like for example ability to pin applications to task bar.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/solus-project/budgie-desktop/pull/141#issuecomment-90260102>
>> .
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/solus-project/budgie-desktop/pull/141#issuecomment-90304629

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by ikeydoherty** [comment]
Eh, closing this, sorry. Applets will get individual settings but I'm not introducing inconsistent usage patterns

**Pull request closed without merging**
