### PR TITLE
[WIP] New Budgie Menu Concept

### PR DESCRIPTION
**Pull request by prateekmedia**
Screenshot from 2021-02-17 20:50:32
## Description
<Info on what this pull request adds>
New Budgie Menu Concept based on orignal menu.  

- [x] Grid View for apps
- [x] Power Strip
- [x] Search Functionality

### TO BE DONE
- [ ] Fix sorting
- [ ] Fix Headers
- [ ] Fix Categories switcher
- [ ] Make power strip a choice, fix duplicate session key detected error while using with userSwitcher
- [ ] Make less rebuilds when searching and Make fix width menu
- [ ] Remove extra spacing by trimming the name of the App

***Any Edits || Suggestion's are welcome.***

### How to test
You can `git clone --depth=1` my repo and then follow the `wiki` on how to build budgie desktop

**Linked Discussion : https://discuss.getsol.us/d/6350-hows-the-menu/**

### Submitter Checklist

- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Built budgie-desktop and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
While I appreciate the commit, Budgie Menu is going to be fundamentally re-architected for 10.5.3 and I do not desire to introduce any additional code until that happens.

Building on this, I already have design plans for a Budgie Menu with both list and grid layouts and this isn't quite it. I appreciate the effort so far, but I won't be landing this since I'd be adopting code that I'd just have to rewrite anyways.

I would encourage you to communicate with me about these sorts of PRs in the future to help avoid any potential wasted effort.

**Comment by prateekmedia** [comment]
> I would encourage you to communicate with me about these sorts of PRs in the future to help avoid any potential wasted effort.

Where to communicate from?

**Comment by JoshStrobl** [comment]
I'm regularly available in the [Solus IRC channels](https://getsol.us/articles/contributing/getting-involved/en/#irc) as well as the `#budgie-desktop-dev` one.

**Comment by Drsheppard01** [comment]
Budgie Menu realized as applet. Can this also be implemented as an (other) applet?

**Comment by EbonJaeger** [comment]
@Drsheppard01 yes. Budgie Menu is just an applet. Another applet can be made to serve the same purpose if someone has the know how to make one.

**Pull request closed without merging**
