### PR TITLE
Ignore notifications

### PR DESCRIPTION
**Pull request by mank319**
My pull request addresses #301 by making it possible to add "spam apps" in terms of `dconf` settings.

### CODE REVIEW

**Comment by JoshStrobl** [comment]
I don't really think doing a complete blacklist to appeal to a single user's opinion on what shouldn't be in the notifications is the **wrong** way of implementing this. Personally, I use several of the music applications you're blacklisting in this PR and seeing notifications disappear for them would completely detract from the user experience.

Having a method to specify what applications should be ignored, graphically, is a preferred option instead.

**Comment by mank319** [comment]
They are not disappearing completely. You will still see popups.
They simply won't trigger the "unread notification red clock icon" and won't flood your notification list in Raven.

**Comment by mank319** [comment]
And of course a graphical front end to tweak the `dconf` entry would be a possible addition to this :wink: 

By the way: Lollypop and Gnome Music where already blocked before. I simply moved the definition of the "spam apps" list from a hardcoded array to a `dconf` setting.

**Comment by JoshStrobl** [comment]
Right, I misunderstood this as blocking the notifications themselves. Continue on good sir :P

**Comment by ikeydoherty** [comment]
Cheers!

**Pull request merged**
