### PR TITLE
Add mark when audio overdrive activate

### PR DESCRIPTION
**Pull request by yursan9**
the marks

### CODE REVIEW

**Comment by JoshStrobl** [comment]
This looks a bit janky given the alignment. @tista500 is this something we can fix via theming?

**Comment by yursan9** [comment]
There is mark.bottom class in Gtk.Scale

**Comment by JoshStrobl** [comment]
> If you fix from theming, I guess it will fix the volume slider in Gnome Control Center too.

Not necessarily, if it was going to be theming-side it'd likely be in the specific selectors `box.audio-widget`

**Comment by Jacalz** [comment]
Otherwise it could probably be good enough with a little bump in the slider that just has some snappiness to it, instead of using a visual mark.

**Comment by tista500** [comment]
@JoshStrobl,

Hmm, we can enforce the vertically centered alignment of troughs by hiding label node like this:
screenshot from 2018-08-07 15-41-51

Gtk+ computes the allocation height of scale node with that extra `mark label` node height by default. So easiest way is hiding label via `font-isze: 0;` property inside the themes...

**Comment by JoshStrobl** [comment]
@tista500 If that's not something you're opposed to doing (or if you disagree with how it looks, Adapta is your theme after all), I'll land this PR. Personally I don't have an issue with hiding the label, it's something I can do for the internal styling post-merge. If we can set a color for the mark itself so it stands out more, that'd be grand as well

**Comment by tista500** [comment]
>  Personally I don't have an issue with hiding the label

Agreed. I don't have either.

> If we can set a color for the mark itself so it stands out more, that'd be grand as well

We also can re-color that `mark indicator` via `color` property from theme-side, so I also think this PR can be merged.

Regards.

**Comment by JoshStrobl** [comment]
Merged. Thanks @yursan9 for the PR, @Jacalz for the feedback (unfortunately some of functionality doesn't exist in Gtk.Scale), and @tista500 for continued support of Budgie in Adapta and the feedback :+1:

**Comment by tista500** [comment]
Forgot to mention, Josh.

We might need to do a bit more work for OSD windows:
screenshot from 2018-08-07 17-39-25

Currently OSD GtkProgressBar is truncated with 100% gain maximum. Symbolic icon seems to switch to overdrive-mode properly though...

Here is our Gnome-Shell theming for overdrive-mode OSD:
gnome-shell-overdrive

Regards.

**Comment by JoshStrobl** [comment]
Thanks @tista500 for the report, I'll be sure to get that bug fixed.

**Pull request merged**
