### PR TITLE
Check if schema is defined for volume slider changes #1544

### PR DESCRIPTION
**Pull request by fossfreedom**
resolves the above issue

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Is this key something that's deprecated / not supported in future GSD releases?

**Comment by fossfreedom** [comment]
As far as I can gather sometime recently someone implemented a more than 100% volume thingy. Code was apparently rejigged. 

Correct me if I am wrong but it looks like the same slider widget is used for both main volume and the microphone widget.

So the gnome sound schema apparently is needed for the main volume slider... but when the same code is run through for the microphone the settings var is not defined ... odd bit of if then clause in the init method of the widget.

I suppose if we are being purist here really should have a base slider widget and two derived classes... kind of a much bigger rijig.

**Comment by JoshStrobl** [comment]
> Correct me if I am wrong but it looks like the same slider widget is used for both main volume and the microphone widget.

Yes however the function responsible, which is `on_volume_safety_changed`, is only used by the output-type sound SoundWidget. See line 95.

> but when the same code is run through for the microphone

It isn't though.

> I suppose if we are being purist here really should have a base slider widget and two derived classes

We already have a widget type for the SoundWidget, passed during construction, which is `c_widget_type`, which then gets assigned to `widget_type`.

**Comment by fossfreedom** [comment]
> Is this key something that's deprecated / not supported in future GSD releases?

It seems this 100% key was introduced very recently at the end of last year.  There is a bit of discussion here https://bugzilla.gnome.org/show_bug.cgi?id=790281

So educated guess - its pretty new so it would be very surprising to be deprecated anytime soon.

**Comment by JoshStrobl** [comment]
Closing since patch shouldn't be unnecessary, given how SoundWidget is implemented (schema is never defined for input since it's never needed for it).

**Pull request closed without merging**
