### PR TITLE
Added select-able menu height to budgie-menu applet

### PR DESCRIPTION
**Pull request by sparkylein**
Added select-able menu height to budgie-menu applet (switch between default and screen height)

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Not entirely sure you got the memo: https://github.com/solus-project/budgie-desktop/issues/501

**Comment by sparkylein** [comment]
Thanks, I've seen the memo. I thought it's only enforced on new stuff and not mods of current vala code. :)

**Comment by sparkylein** [comment]
BTW: glad you can see my pull request, was unsure as it's my first time doing it this way...

**Comment by ikeydoherty** [comment]
I vaguely recollect saying I wouldn't accept a PR for this full-screen-menu change in your other bug

**Comment by sparkylein** [comment]
Ikey, you said: "Yeah this personally is not something I want to see in Budgie by default.
With that said, if you want a proper full screen launcher applet, we do have a public API which will enable this :)"

I didn't want a full screen launcher, just a longer app list in the menu.
My implementation leaves the default size as is. If someone wants a longer list he has to switch it on on purpose.

Sorry if I misunderstood you.

**Comment by ikeydoherty** [comment]
Sorry I can't merge this in right now. Long story short I'm gonna rewrite Budgie Menu in the near future, and I wanna do it properly from the ground up, and this change would definitely get lost in the process. We need to improve settings and the menu window itself

**Pull request closed without merging**
